package org.example.herenciaYexcepciones.excepciones;
// OTRAS EXCEPCIONES

/* LAS EXCEPCIONES CHEQUEADAS (TAMBINE LLAMDAS LOGICAS) SON AQUELLAS DE LAS
   CUALES PODRIAMOS RECUPERARNOS.

   POR EJEMPLO, SI QUISIERAMOS COMUNICARNOS CON UNA BASE DE DATOS QUE ESTA CAIDA
   TEMPORALMENTE, ENTONCES ESPERAMOS UNOS SEGUNDOS Y HACEMOS REINTENTO.

   UNA EXCEPTION CHEQUEADA ES CAPTURADA EN TIEMPO DE COMPILACION POR EL COMPILADOR
   Y ESTE TE OBLIGA A MANEJAR DICHA EXCEPCION */

public class Checked {

}
